### ISSUE TITLE
Quotes around energy values

### ISSUE THREAD

**Issue by GeertenV** [gvsoc/gvsoc-pulp#17]
I used pulp/chips/pulp_open/power_models/l1/l1.json as an example to add power/energy to my own system.
However I noticed it would not work if there are quotes around the values.
Should these quotes simply be removed or is there something wrong in the mechanism that parses these parameters?

**Comment by haugoug** [comment]
Indeed that's better to support it, I've just merged a fix, that should now work.
I've also included your memory power numbers in the tutorial to show how to use existing power models.
